### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by DarkRewar** [EduardMalkhasyan/Serializable-Dictionary-Unity#2]
Hello, your code works really nice, but the repo doesn't have any license yet.
Legally, no one can use your project (even in free use).
Could it be possible to add one please?
Thank you

**Comment by EduardMalkhasyan** [comment]
Hello thanks for noticing it, I didn't know that )) I will add now!

**Comment by EduardMalkhasyan** [comment]
Done!
