### ISSUE TITLE
Label mispositioned (appears on top of the foldout arrow) in Unity 6 Preview 6.0.7

### ISSUE THREAD

**Issue by yxx10** [EduardMalkhasyan/Serializable-Dictionary-Unity#4]
Perhaps an issue with an API change, but in Unity 6.0.7 (which is still in preview), the label from the foldout appears on top of the arrow. Can be worked around by just making this change to the `DisplayName` method in the `SerializableDictionaryDrawer` class:

    GUI.color = Color.white;
    //GUI.Label(headerRect, prop.displayName); <- original

    var labelRect = headerRect;
    labelRect.x += 12;
    GUI.Label(labelRect, prop.displayName); // <- workaround

    GUI.color = Color.white;
    GUI.skin.label.fontSize = 12;
    GUI.skin.label.fontStyle = FontStyle.Normal;
    GUI.skin.label.alignment = TextAnchor.MiddleLeft;

**Comment by EduardMalkhasyan** [comment]
Ok thanks @yxx10 I will check today!

**Comment by EduardMalkhasyan** [comment]
Hello @yxx10 new version has the fix - [V_2_02](https://github.com/EduardMalkhasyan/Serializable-Dictionary-Unity/releases)

Works for 2021, 2022 and above 

Your right there was API change for 2022 and above, thanks for advice!
