### ISSUE TITLE
 SerializableDictionary<string, object> unable to parse objects

### ISSUE THREAD

**Issue by OdincoGaming** [EduardMalkhasyan/Serializable-Dictionary-Unity#6]
ive tried everything, explicitly casting, making a generically typed GetValue method, basically anything the top 100 searches on bing and google suggested and without fail every single time I just get null when using object as the value.

am I maybe doing something wrong? or is actually a limitation of this plugin?

**Comment by EduardMalkhasyan** [comment]
Hello @OdincoGaming  as I know generally you cant serialize `[SerializeField] private object data;` object by it self in Unity 
you need to specify what type it is exactly, so yes its also limitation of this plugin

**Comment by EduardMalkhasyan** [comment]
I don't know if you need this but look at this class it can be serialized 
![image](https://github.com/user-attachments/assets/57945f64-d331-4322-b817-2c04b384e235)
