### ISSUE TITLE
[Bug] Global Modification

### ISSUE THREAD

**Issue by Kiryonn** [EduardMalkhasyan/Serializable-Dictionary-Unity#7]
Somehow, all dictionaries are changed globally.

![image](https://github.com/user-attachments/assets/f9f86654-7934-4ce6-99e3-80466726f28e)

```cs
[Serializable]
public class CityType
{
	public string Name;
	public Vector2Int PopulationRange;
	public SerializableDictionary<string, int> Buildings = new();
}
```

**Comment by EduardMalkhasyan** [comment]
@Kiryonn 
Yes please do it like this, in beginning declare serializable dict like this, start with dict not inside dict 

```csharp
 public SerializableDictionary<string, CityType> cities;

 [Serializable]
 public class CityType
 {
     public string Name;
     public Vector2Int PopulationRange;
     public string buildingName;
     public int buildingIndex;
 }
```

![image](https://github.com/user-attachments/assets/8547fa75-87fd-40e1-ade8-060aeb11c7fb)
This is the weak point of this plugin.

**Comment by Kiryonn** [comment]
This is not the behavior I'm searching for. Tho that's a cool plugin that can make my life easier. Hope Unity one day will have those by default like Godot does.

**Comment by EduardMalkhasyan** [comment]
Yeah I understand. This plugin made for making some architecture realization easier, but it has limitations and issues, but it can help on development!
