### ISSUE TITLE
Can't drag the divider between key and value in the inspector

### ISSUE THREAD

**Issue by ofir-b-HDEG** [EduardMalkhasyan/Serializable-Dictionary-Unity#8]
When I try to drag the divider between the key and value, I get an error in the console.

It seems not that important, but when you have nested objects in the dictionary, it begins to be very space consuming, and shrinking the key width in the inspector can help a lot.

![2024-11-28 10-31-37](https://github.com/user-attachments/assets/bbfbda2f-63e9-4b6a-ab2b-6b8c0d111e8e)

Here is the error from the console:
NullReferenceException: Object reference not set to an instance of an object
ProjectTools.SerializableDictionaryDrawer.<DrawListElement>g__Divider|3_4 (ProjectTools.SerializableDictionaryDrawer+<>c__DisplayClass3_0& ) (at Assets/Plugins/SerializableDictionary/SerializableDictionaryDrawer.cs:312)
ProjectTools.SerializableDictionaryDrawer.DrawListElement (UnityEngine.Rect rect, System.Int32 index, System.Boolean isActive, System.Boolean isFocused) (at Assets/Plugins/SerializableDictionary/SerializableDictionaryDrawer.cs:319)
UnityEditorInternal.ReorderableList.DoListElements (UnityEngine.Rect listRect, UnityEngine.Rect visibleRect) (at <8d33a6384e1148858f2e669234fa89ff>:0)
UnityEditorInternal.ReorderableList.DoList (UnityEngine.Rect rect, UnityEngine.Rect visibleRect) (at <8d33a6384e1148858f2e669234fa89ff>:0)
UnityEditorInternal.ReorderableList.DoList (UnityEngine.Rect rect) (at <8d33a6384e1148858f2e669234fa89ff>:0)
ProjectTools.SerializableDictionaryDrawer.<OnGUI>g__List|0_1 (ProjectTools.SerializableDictionaryDrawer+<>c__DisplayClass0_0& ) (at Assets/Plugins/SerializableDictionary/SerializableDictionaryDrawer.cs:144)
ProjectTools.SerializableDictionaryDrawer.OnGUI (UnityEngine.Rect rect, UnityEditor.SerializedProperty prop, UnityEngine.GUIContent label) (at Assets/Plugins/SerializableDictionary/SerializableDictionaryDrawer.cs:150)
UnityEditor.PropertyDrawer.OnGUISafe (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at <8d33a6384e1148858f2e669234fa89ff>:0)
UnityEditor.PropertyHandler.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren, UnityEngine.Rect visibleArea) (at <8d33a6384e1148858f2e669234fa89ff>:0)
UnityEditor.PropertyHandler.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren) (at <8d33a6384e1148858f2e669234fa89ff>:0)
UnityEditor.PropertyHandler.OnGUILayout (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren, UnityEngine.GUILayoutOption[] options) (at <8d33a6384e1148858f2e669234fa89ff>:0)
UnityEditor.EditorGUILayout.PropertyField (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren, UnityEngine.GUILayoutOption[] options) (at <8d33a6384e1148858f2e669234fa89ff>:0)
UnityEditor.EditorGUILayout.PropertyField (UnityEditor.SerializedProperty property, System.Boolean includeChildren, UnityEngine.GUILayoutOption[] options) (at <8d33a6384e1148858f2e669234fa89ff>:0)
UnityEditor.UIElements.PropertyField.<CreatePropertyIMGUIContainer>b__44_0 () (at <8d33a6384e1148858f2e669234fa89ff>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.IMGUIContainer.ProcessEvent (UnityEngine.UIElements.EventBase evt) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtCurrentTargetAndPhase (UnityEngine.UIElements.EventBase evt) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <2e666ac28cd74471bd9d2ff0cb016e9e>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <f1e27903dfe2495f8894a6c1c00b9ffe>:0)

**Comment by EduardMalkhasyan** [comment]
Hello @ofir-b-HDEG  thanks for noticing, here is hot fix version, [2.0.4](https://github.com/EduardMalkhasyan/Serializable-Dictionary-Unity/releases/tag/v2.0.4), I just temporarily disabled the key divider section, but value can be changed

**Comment by ofir-b-HDEG** [comment]
Just for everyone that needs it, on version 2.0.4, you can change the divider value in the file `Assets/Plugins/SerializableDictionary.cs` on line 228:
```csharp
var dividerPosition = 0.25f;
```
I've seen better implementations. But thanks for the quick fix.
