### ISSUE TITLE
Serializable classes do not show up properly as keys, but do as values  

### ISSUE THREAD

**Issue by AttoBlaze** [EduardMalkhasyan/Serializable-Dictionary-Unity#9]
When i use a serializable class as a key, practically only the class field names shows up in the editor. The dictionary is still fully functional, but practically unusable, as it is impossible to properly see any fields of the key in the editor. Using the same class as a value, however, has no issues.

As key:
![image](https://github.com/user-attachments/assets/a4388515-abba-4176-8a6e-5b01288e966f)
![image](https://github.com/user-attachments/assets/37ba4a1d-1df0-4294-bc11-1e7ddfce8d4a)

As value:
![image](https://github.com/user-attachments/assets/e7e0c4e7-91d9-4041-b926-f3e7eed27417)
![image](https://github.com/user-attachments/assets/3719b9f4-48cc-4cee-9187-77487b447620)

**Comment by EduardMalkhasyan** [comment]
@AttoBlaze  Yes this is some kind of limitation of this plugin, to be honest I never thought that class can be used as key in dictionary, because its expensive and not like static unit as int or string or like that Types
